-- Arbazis tábla létrehozása
CREATE TABLE IF NOT EXISTS arbazis (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    penznemid INTEGER NOT NULL UNIQUE,
    arfolyam REAL NOT NULL,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    FOREIGN KEY (penznemid) REFERENCES penznem(id) ON DELETE CASCADE ON UPDATE CASCADE
);

-- Árfolyam adatok beszúrása az alapértelmezett értékekkel
INSERT OR IGNORE INTO arbazis (penznemid, arfolyam, created_at, updated_at) 
SELECT id, 1.0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP FROM penznem WHERE nev = 'HUF'
UNION ALL
SELECT id, 415.0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP FROM penznem WHERE nev = 'EUR'
UNION ALL
SELECT id, 380.0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP FROM penznem WHERE nev = 'USD'
UNION ALL
SELECT id, 480.0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP FROM penznem WHERE nev = 'GBP'
UNION ALL
SELECT id, 420.0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP FROM penznem WHERE nev = 'CHF'
UNION ALL
SELECT id, 2.5, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP FROM penznem WHERE nev = 'JPY'
UNION ALL
SELECT id, 52.0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP FROM penznem WHERE nev = 'CNY'
UNION ALL
SELECT id, 250.0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP FROM penznem WHERE nev = 'AUD'
UNION ALL
SELECT id, 280.0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP FROM penznem WHERE nev = 'CAD'
UNION ALL
SELECT id, 55.7, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP FROM penznem WHERE nev = 'DKK'
UNION ALL
SELECT id, 37.0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP FROM penznem WHERE nev = 'NOK'
UNION ALL
SELECT id, 38.0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP FROM penznem WHERE nev = 'SEK'
UNION ALL
SELECT id, 95.0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP FROM penznem WHERE nev = 'PLN'
UNION ALL
SELECT id, 16.0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP FROM penznem WHERE nev = 'CZK'
UNION ALL
SELECT id, 83.0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP FROM penznem WHERE nev = 'RON'
UNION ALL
SELECT id, 212.0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP FROM penznem WHERE nev = 'BGN'
UNION ALL
SELECT id, 55.5, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP FROM penznem WHERE nev = 'HRK'
UNION ALL
SELECT id, 3.5, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP FROM penznem WHERE nev = 'RUB'
UNION ALL
SELECT id, 4.5, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP FROM penznem WHERE nev = 'INR'
UNION ALL
SELECT id, 22.0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP FROM penznem WHERE nev = 'MXN'
UNION ALL
SELECT id, 283.0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP FROM penznem WHERE nev = 'SGD'
UNION ALL
SELECT id, 48.5, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP FROM penznem WHERE nev = 'HKD'
UNION ALL
SELECT id, 230.0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP FROM penznem WHERE nev = 'NZD'
UNION ALL
SELECT id, 21.0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP FROM penznem WHERE nev = 'ZAR'
UNION ALL
SELECT id, 103.5, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP FROM penznem WHERE nev = 'AED'
UNION ALL
SELECT id, 101.0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP FROM penznem WHERE nev = 'SAR';
